---
# syncthing
- name: Syncthing repo key
  ansible.builtin.get_url:
    url: "https://syncthing.net/release-key.gpg"
    dest: /usr/share/keyrings/syncthing-archive-keyring.gpg
    mode: "0644"

- name: Syncthing repository stat
  ansible.builtin.stat:
    path: "/etc/apt/sources.list.d/syncthing.list"
  register: stat_result

- name: Syncthing repository remove
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/syncthing.list"
    state: absent
  when: stat_result.stat.exists 

- name: Syncthing repository add
  ansible.builtin.apt_repository:
    validate_certs: false
    repo: "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable"
    state: present
    filename: syncthing
    update_cache: true

- name: Syncthing
  ansible.builtin.apt:
    name:
      - syncthing
    state: present
