---
- name: VScodium repo key
  ansible.builtin.get_url:
    url: "https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg"
    dest: /usr/share/keyrings/vscodium-archive-keyring.asc
    mode: "0644"
- name: VScodium repo list
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/vscodium.list"
    state: absent
- name: VScodium repo
  ansible.builtin.apt_repository:
    repo: "deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.asc ] https://download.vscodium.com/debs vscodium main"
    filename: vscodium
    state: present
    validate_certs: false
    update_cache: true
- name: VScodium
  ansible.builtin.apt:
    name:
      - codium
